- type: entity
  id: SpawnPointMetroResident
  parent: SpawnPointJobBase
  name: Житель Метро
  components:
  - type: SpawnPoint
    job_id: MetroResident
  - type: Sprite
    layers:
      - state: green
      - state: passenger